// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models;

public partial class PuestosDeTrabajo
{
    public int IdPuesto { get; set; }

    public string Descripcion { get; set; }

    public string Titulo { get; set; }

    public bool Disponible { get; set; }

    public virtual ICollection<EmpresasPuestos> EmpresasPuestos { get; set; } = new List<EmpresasPuestos>();

    public virtual ICollection<PuestosDeTrabajoPostulaciones> PuestosDeTrabajoPostulaciones { get; set; } = new List<PuestosDeTrabajoPostulaciones>();
}