// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models;

public partial class TiposAdmin
{
    public int IdTipoAdmin { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Admins> Admins { get; set; } = new List<Admins>();
}