// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models;

public partial class Alumnos
{
    public string Dni { get; set; }

    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public string Celular { get; set; }

    public string Nacionalidad { get; set; }

    public string Pais { get; set; }

    public string Ciudad { get; set; }

    public string Direccion { get; set; }

    public virtual Usuarios IdUsuarioNavigation { get; set; }

    public virtual ICollection<Postulaciones> Postulaciones { get; set; } = new List<Postulaciones>();
}