// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models
{
    public partial class Empresas
    {
        public Empresas()
        {
            PuestosDeTrabajo = new HashSet<PuestosDeTrabajo>();
        }

        public int IdEmpresa { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }

        public virtual Usuarios IdUsuarioNavigation { get; set; }
        public virtual ICollection<PuestosDeTrabajo> PuestosDeTrabajo { get; set; }
    }
}