// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models
{
    public partial class EmpresasPuestos
    {
        public int IdEmpresaPuestos { get; set; }
        public int IdEmpresa { get; set; }
        public int IdPuestosDeTrabajo { get; set; }

        public virtual Empresas IdEmpresaNavigation { get; set; }
    }
}