// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models
{
    public partial class EstadosPostulacion
    {
        public EstadosPostulacion()
        {
            Postulaciones = new HashSet<Postulaciones>();
        }

        public int IdEstado { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Postulaciones> Postulaciones { get; set; }
    }
}