// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models;

public partial class Postulaciones
{
    public int IdPostulacion { get; set; }

    public string DniAlumno { get; set; }

    public int Estado { get; set; }

    public virtual Alumnos DniAlumnoNavigation { get; set; }

    public virtual EstadosPostulacion EstadoNavigation { get; set; }

    public virtual ICollection<PuestosDeTrabajoPostulaciones> PuestosDeTrabajoPostulaciones { get; set; } = new List<PuestosDeTrabajoPostulaciones>();
}