// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models
{
    public partial class TiposUsuarios
    {
        public int IdTipo { get; set; }
        public string Descripcion { get; set; }
    }
}