// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BolsaDeTrabajo.Model.Models
{
    public partial class Usuarios
    {
        public Usuarios()
        {
            Admins = new HashSet<Admins>();
            Alumnos = new HashSet<Alumnos>();
            PuestosDeTrabajoPostulaciones = new HashSet<PuestosDeTrabajoPostulaciones>();
            Suscriptores = new HashSet<Suscriptores>();
            Tokens = new HashSet<Tokens>();
        }

        public int IdUsuario { get; set; }
        public string Email { get; set; }
        public string Contrasenia { get; set; }
        public int TipoUsuario { get; set; }
        public int? IdPuestosDeTrabajoPostulaciones { get; set; }
        public string CuitCuil { get; set; }
        public string Carrera { get; set; }

        public virtual PuestosDeTrabajoPostulaciones IdPuestosDeTrabajoPostulacionesNavigation { get; set; }
        public virtual ICollection<Admins> Admins { get; set; }
        public virtual ICollection<Alumnos> Alumnos { get; set; }
        public virtual ICollection<PuestosDeTrabajoPostulaciones> PuestosDeTrabajoPostulaciones { get; set; }
        public virtual ICollection<Suscriptores> Suscriptores { get; set; }
        public virtual ICollection<Tokens> Tokens { get; set; }
    }
}